openapi: 3.0.0
servers:
  - url: http://localhost:8000/api/v1
tags:
  - name: card_transactions

definitions:
  CardTransaction:
    type: object
    properties:
      id:
        type: string
      card_number:
        type: string
      transaction_type:
        type: string
      description:
        type: string
      currency:
        type: string
      amount:
        type: string
      status:
        type: string
      datetime_created:
        type: string
        format: date
      datetime_updated:
        type: string
        format: date

parameters:
  - name: amount
    in: body
    type: object
    description: Updates the status of a virtual card
    properties:
      amount:
        type: string
        example: 1000
      description:
        type: string
        example: Card funding

responses:
  '200':
    description: card has been funded successfully
  '400':
    description: Not a dictionary
  '500':
    description: Unable to perform transaction
