openapi: 3.0.0
servers:
  - url: http://localhost:8000/api/v1
tags:
  - name: cards
get:
  description: Returns all Nairalink virtual cards
responses:
  '200':
    description: Ok
  '500':
    description: Internal Server Error
