openapi: 3.0.0
tags:
  - name: Card service server status from docs
get:
  description: None
responses:
  '200':
    description: Successful response
  '400':
    description: Bad Request
  '500':
    description: Internal Server Error
