name: Card Service CI workflow

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: python:3.8-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pycodestyle
        run: |
          pycodestyle --show-source --show-pep8 ./**/*.py